version: "3"

services:
  api:
    build: ./src/app
    command: go run server.go
    ports:
      - "8080:8080"
    volumes:
      - ./src/app:/go/src/app
      - ./share:/share
    environment:
      VIRTUAL_HOST: "go-api.docker"
      PGHOST: "db"
      PGPORT: "5432"
      PGUSER: "postgres"
      PGDBNAME: "mydb"
      PGPASSWORD: "password"
    depends_on:
      - db
    entrypoint: /share/wait-for-postgres.sh db

  db:
    image: postgres
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    container_name: "postgres-db"
    volumes:
      - postgres-data:/path/to/data
    expose:
      - "5432"

  pgweb:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgres://postgres:password@db:5432/mydb?sslmode=disable
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
