version: "3"

services:
  api:
    build: ./src/app
    command: go run server.go
    ports:
      - "3000:8080"
    volumes:
      - ./src/app:/go/src/app
    environment:
      VIRTUAL_HOST: "go-api.docker"
      AUTH_DB_HOST: "db"
      AUTH_DB_PORT: "5432"
      AUTH_DB_USER: "postgres"
      AUTH_DB_NAME: "mydb"
      AUTH_DB_PASSWORD: "password"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    container_name: postgres-db
    volumes:
        - postgres-data:/path/to/data
    expose:
      - "5432"

  pgweb:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgres://postgres:password@db:5432/mydb?sslmode=disable
    ports:
      - '8081:8080'
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
